import { supabase } from '../supabase'
import { fetchAllRows, localDayBoundsIso, fetchStaffIdentities } from './shared.js'
import { logApprovalEventRemote } from './auth.js'

export async function logAuditEvent({ branchId, staffId, eventType, detail, meta = {} }) {
  if (!supabase) return null
  const { data, error } = await supabase.rpc('log_audit_event', {
    p_branch_id: branchId || null,
    p_staff_id: staffId || null,
    p_event_type: eventType,
    p_detail: detail || null,
    p_meta: meta,
  })
  if (error) {
    // Soft-fail if migration not applied yet
    if (String(error.message || '').includes('Could not find the function')) return null
    console.warn('audit log failed', error.message)
    return null
  }
  return data
}

/**
 * Record a supervisor/manager sign-off for an action that has no row of its own to carry
 * an `approved_by` column — a cart line removed before the sale exists, a shelf price
 * overridden at the counter. Without this, those approvals left no trace of WHO allowed
 * them, only that the action happened.
 *
 * Actions that already persist an approver (`transactions.void_approved_by`,
 * `sale_refund_lines.approved_by`, `cash_drawer_entries.approved_by`,
 * `shift_adjustments.approved_by`) do NOT go through here — a second record would just
 * be a second thing to keep in sync.
 */
export async function logApprovalEvent({
  branchId,
  requestedBy,
  approvedBy,
  approverName = null,
  approverRole = null,
  action,
  detail = null,
  meta = {},
  deviceId = null,
  clientId = null,
}) {
  const { canSyncWithBackend } = await import('../../offline/reachability')
  const reachable = supabase && (await canSyncWithBackend())
  if (!reachable) {
    const { recordOfflineApprovalAudit } = await import('../../offline/offlineAudit')
    return recordOfflineApprovalAudit({
      branchId,
      requestedBy,
      approvedBy,
      approverName,
      approverRole,
      action,
      detail,
      meta,
      deviceId,
      clientId,
    })
  }
  return logApprovalEventRemote({
    branchId,
    requestedBy,
    approvedBy,
    approverName,
    approverRole,
    action,
    detail,
    meta,
    deviceId,
    clientId,
  })
}

/**
 * Audit trail in range. `limit: null` reads everything.
 *
 * The old hard cap of 500 silently truncated the Login & Audit Trail report — an audit
 * document that quietly drops the oldest events in its own date range is worse than no
 * document, because it reads as complete. Report callers pass null; incidental callers
 * that only want a recent slice still pass a limit.
 */
export async function fetchAuditEvents({ start, end, branchId, limit = 500 } = {}) {
  const { startIso: auditStartIso, endIso: auditEndIso } = localDayBoundsIso(start, end)
  const build = (from, to) => {
    let query = supabase
      .from('audit_events')
      .select('*, staff(full_name), branches(name)')
      .order('created_at', { ascending: false })
      .order('id', { ascending: false })
      .range(from, to)
    if (auditStartIso) query = query.gte('created_at', auditStartIso)
    if (auditEndIso) query = query.lte('created_at', auditEndIso)
    if (branchId) query = query.eq('branch_id', branchId)
    return query
  }
  if (limit == null) {
    const { data, error } = await fetchAllRows(build)
    if (error) throw error
    return data || []
  }
  const { data, error } = await build(0, limit - 1)
  if (error) throw error
  return data || []
}

// Every audit_events row generated by a manager/supervisor approval request — the same
// six source categories RequestNotifications.jsx's bell surfaces while pending
// (fetchPendingApprovals): day-end, cash movement, cart removal (till_action), promo,
// refund, and import-batch revert. Not exported — fetchNotificationHistory is the
// intended entry point so this list and the query stay coupled.
const NOTIFICATION_EVENT_TYPES = [
  'day_end_approved',
  'day_end_reopen',
  'day_end_reopen_requested',
  'day_end_request_declined',
  'day_end_request_cleared',
  'cash_movement_approved',
  'cash_movement_pending',
  'cash_movement_remote_approved',
  'cash_movement_self_recorded',
  'cash_movement_denied',
  'cash_movement_self_approved',
  'cash_movement_resolved',
  'cash_movement_cancelled',
  'cash_movement_reviewed',
  'till_action_requested',
  'till_action_approved',
  'till_action_denied',
  'till_action_self_allowed',
  'till_action_cancelled',
  'promo_approved',
  'promo_rejected',
  'promo_stopped',
  'promo_stop_requested',
  'promo_edit_requested',
  'refund_requested',
  'refund_request_approved',
  'refund_request_rejected',
  'import_revert_requested',
  'import_revert_dismissed',
  'import_reverted',
]

/**
 * Resolved + pending manager/supervisor notification history in range — the audit trail
 * of every item that ever appeared in the RequestNotifications bell. `branchId` null/omitted
 * means network-wide (manager view); pass a branch id to scope to one branch (supervisor view).
 */
export async function fetchNotificationHistory({ start, end, branchId } = {}) {
  const events = await fetchAuditEvents({ start, end, branchId, limit: null })
  return events.filter((e) => NOTIFICATION_EVENT_TYPES.includes(e.event_type))
}

const SECURITY_AUDIT_TYPES = [
  'login',
  'logout',
  'day_end_lock',
  'pin_viewed',
  'company_profile_updated',
]

/** Recent security-relevant audit rows. Never selects PIN or password fields. */
export async function fetchSecurityAuditEvents({ limit = 10, offset = 0 } = {}) {
  if (!supabase) return { rows: [], total: 0 }
  const from = Math.max(0, offset)
  const size = Math.max(1, limit)
  const { data, error, count } = await supabase
    .from('audit_events')
    .select('id, created_at, event_type, detail, staff_id, branch_id, staff(full_name), branches(name)', {
      count: 'exact',
    })
    .in('event_type', SECURITY_AUDIT_TYPES)
    .order('created_at', { ascending: false })
    .order('id', { ascending: false })
    .range(from, from + size - 1)
  if (error) throw error
  return { rows: data || [], total: count ?? 0 }
}

/** Void / refund events. `limit: null` reads everything — see fetchAuditEvents. */
export async function fetchSaleEvents({ start, end, branchId, eventType, limit = 500 } = {}) {
  const { startIso: dayStart, endIso: dayEnd } = localDayBoundsIso(start, end)
  const build = (from, to) => {
    let query = supabase
      .from('sale_events')
      .select('*, branches(name)')
      .order('created_at', { ascending: false })
      .order('id', { ascending: false })
      .range(from, to)
    if (dayStart) query = query.gte('created_at', dayStart)
    if (dayEnd) query = query.lte('created_at', dayEnd)
    if (branchId) query = query.eq('branch_id', branchId)
    if (eventType) query = query.eq('event_type', eventType)
    return query
  }
  let rows
  if (limit == null) {
    const { data, error } = await fetchAllRows(build)
    if (error) throw error
    rows = data || []
  } else {
    const { data, error } = await build(0, limit - 1)
    if (error) throw error
    rows = data || []
  }
  // Resolved separately rather than via a `staff(full_name)` embed — the embed is filtered
  // by `staff`'s own RLS (self row or manager only), so a supervisor viewing a cashier's
  // void/refund got a silently blank "performed by". `fetchStaffIdentities` goes through
  // resolve_staff_identities(), which grants a supervisor their own branch. voidSale also
  // stashes the approver id in payload.approved_by, resolved the same way.
  const who = await fetchStaffIdentities([
    ...rows.map((row) => row.staff_id),
    ...rows.map((row) => row.payload?.approved_by),
  ]).catch(() => ({}))
  return rows.map((row) => {
    const performer = who[row.staff_id]
    const approver = who[row.payload?.approved_by]
    return {
      ...row,
      staff: performer ? { full_name: performer.name } : row.staff,
      ...(approver ? { approver_name: approver.name, approver_role: approver.role } : null),
    }
  })
}
